name: backend
description: A server app using the shelf package.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.2

dependencies:
  args: ^2.3.0
  protos:
    path: ../protos
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
