name: proto_bloc
description: A demo combining the power of protobuf with the power of bloc.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
